import React, { useState } from 'react';
import { DogecoinConf } from '../types';
import { sounds } from '../services/audio';

interface AdminConsoleModalProps {
  isOpen: boolean;
  onClose: () => void;
  config: DogecoinConf;
  nodeStatus: 'connected' | 'emulated';
  onSaveConfig: (newConf: Partial<DogecoinConf>) => Promise<void>;
  onTestRpc: () => Promise<{ connected: boolean; latencyMs: number; error?: string; data?: unknown }>;
  onExecRpc: (method: string, params?: unknown[]) => Promise<{ success: boolean; result?: unknown; error?: string; simulated?: boolean }>;
}

export const AdminConsoleModal: React.FC<AdminConsoleModalProps> = ({
  isOpen,
  onClose,
  config,
  nodeStatus,
  onSaveConfig,
  onTestRpc,
  onExecRpc,
}) => {
  const [formData, setFormData] = useState<DogecoinConf>({ ...config });
  const [houseAddressInput, setHouseAddressInput] = useState<string>(config.houseAddress);
  const [activeTab, setActiveTab] = useState<'config' | 'cli' | 'export'>('config');

  const [saving, setSaving] = useState<boolean>(false);
  const [saveMessage, setSaveMessage] = useState<string | null>(null);

  // RPC Test State
  const [testingRpc, setTestingRpc] = useState<boolean>(false);
  const [testResult, setTestResult] = useState<{ connected: boolean; latencyMs: number; error?: string } | null>(null);

  // CLI State
  const [cliCommand, setCliCommand] = useState<string>('getmininginfo');
  const [cliOutput, setCliOutput] = useState<string>('// Dogecoin Core RPC Console initialized.\n// Try: getbalance, getmininginfo, getnetworkhashps, getblockchaininfo, getnewaddress');
  const [executingCli, setExecutingCli] = useState<boolean>(false);

  if (!isOpen) return null;

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setSaveMessage(null);
    sounds.playLever();

    try {
      await onSaveConfig({
        ...formData,
        houseAddress: houseAddressInput.trim(),
      });
      setSaveMessage('DOGECOIN.CONF & CASHIER OPTIONS UPDATED SUCCESSFULLY');
      sounds.playCoinClink();
    } catch (err: unknown) {
      setSaveMessage(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setSaving(false);
    }
  };

  const handleRunRpcTest = async () => {
    setTestingRpc(true);
    sounds.playRelayClick();
    try {
      const res = await onTestRpc();
      setTestResult(res);
      if (res.connected) {
        sounds.playCoinClink();
      }
    } finally {
      setTestingRpc(false);
    }
  };

  const handleRunCli = async () => {
    if (!cliCommand.trim()) return;
    setExecutingCli(true);
    sounds.playRelayClick();

    const parts = cliCommand.trim().split(' ');
    const method = parts[0];
    const params = parts.slice(1);

    try {
      const res = await onExecRpc(method, params);
      setCliOutput((prev) => {
        const timestamp = new Date().toLocaleTimeString();
        const header = `\n[${timestamp}] > ${cliCommand} ${res.simulated ? '(Daemon offline - Emulated result)' : '(Live RPC)'}:\n`;
        const body = JSON.stringify(res.result || res.error, null, 2);
        return prev + header + body;
      });
    } catch (err: unknown) {
      setCliOutput((prev) => prev + `\nError: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setExecutingCli(false);
    }
  };

  const dogecoinConfRaw = `# dogecoin.conf - Generated by Dogecoin Core 3-Rig Cabinet
connect=${formData.connect}
listen=${formData.listen}
server=${formData.server}
listenonion=${formData.listenonion}
discover=${formData.discover}
dnsseed=${formData.dnsseed}
txindex=${formData.txindex}
port=${formData.port}
rpcallowip=${formData.rpcallowip}
rpcport=${formData.rpcport}
rpcuser=${formData.rpcuser}
rpcpassword=${formData.rpcpassword}
`;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-xs">
      <div className="cabinet-panel border-2 border-amber-500 w-full max-w-3xl max-h-[92vh] overflow-y-auto relative shadow-2xl p-5 text-[#f59e0b]">
        {/* Corner Rivets */}
        <div className="absolute top-2 left-2 rivet" />
        <div className="absolute top-2 right-2 rivet" />
        <div className="absolute bottom-2 left-2 rivet" />
        <div className="absolute bottom-2 right-2 rivet" />

        {/* Modal Header */}
        <div className="flex items-center justify-between pb-3 mb-4 border-b border-[#3b3e4e]">
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 bg-amber-500 rounded-sm shadow-[0_0_8px_#f59e0b]" />
            <h2 className="text-lg font-tech font-bold uppercase tracking-wider text-amber-glow">
              DOGECOIN CORE · ADMIN MASTER CONSOLE
            </h2>
          </div>
          <button
            onClick={() => {
              onClose();
              sounds.playRelayClick();
            }}
            className="px-2 py-1 bg-[#1c1d24] hover:bg-[#282a35] border border-[#3b3e4e] text-zinc-300 font-mono text-xs"
          >
            [ESC] CLOSE
          </button>
        </div>

        {/* Tabs */}
        <div className="flex items-center gap-2 mb-4 border-b border-[#2b2d38] pb-2">
          <button
            onClick={() => setActiveTab('config')}
            className={`px-3 py-1.5 text-xs font-tech font-bold uppercase border transition-all ${
              activeTab === 'config'
                ? 'bg-[#291e07] border-[#f59e0b] text-[#fbbf24]'
                : 'bg-[#121318] border-[#2b2d38] text-zinc-400'
            }`}
          >
            DOGECOIN.CONF & WALLET
          </button>
          <button
            onClick={() => setActiveTab('cli')}
            className={`px-3 py-1.5 text-xs font-tech font-bold uppercase border transition-all ${
              activeTab === 'cli'
                ? 'bg-[#291e07] border-[#f59e0b] text-[#fbbf24]'
                : 'bg-[#121318] border-[#2b2d38] text-zinc-400'
            }`}
          >
            CORE JSON-RPC TERMINAL
          </button>
          <button
            onClick={() => setActiveTab('export')}
            className={`px-3 py-1.5 text-xs font-tech font-bold uppercase border transition-all ${
              activeTab === 'export'
                ? 'bg-[#291e07] border-[#f59e0b] text-[#fbbf24]'
                : 'bg-[#121318] border-[#2b2d38] text-zinc-400'
            }`}
          >
            EXPORT DOGECOIN.CONF
          </button>
        </div>

        {/* TAB 1: Config Form */}
        {activeTab === 'config' && (
          <form onSubmit={handleSave} className="space-y-4">
            {/* Slot for Admin to Insert Dogecoin Address */}
            <div className="bg-[#141208] border-2 border-amber-600/70 p-3.5 space-y-2">
              <div className="flex justify-between items-center">
                <label className="text-xs font-tech font-bold uppercase text-[#fbbf24] tracking-wide">
                  APP MASTER DOGECOIN WALLET ADDRESS (HOUSE POOL)
                </label>
                <span className="text-[10px] font-mono text-amber-500">
                  ALL 3 RIGS DEPOSIT MINING HERE
                </span>
              </div>
              <input
                type="text"
                value={houseAddressInput}
                onChange={(e) => setHouseAddressInput(e.target.value)}
                placeholder="DM9..."
                className="w-full bg-[#0a0b0e] border border-[#f59e0b66] focus:border-amber-400 px-3 py-2 text-xs font-mono text-[#fbbf24] outline-none"
              />
              <div className="text-[11px] text-zinc-400 font-mono">
                The House retains a strict <strong className="text-amber-400">25.00% cut</strong> of all mining, and automatically dispatches the remaining <strong className="text-emerald-400">75.00%</strong> to each miner&apos;s address every ~60 seconds via Dogecoin Core <code className="text-amber-300">sendtoaddress</code>.
              </div>
            </div>

            {/* Dogecoin Core RPC & Network Options */}
            <div className="bg-[#0b0c10] border border-[#2b2d38] p-3.5 space-y-3">
              <div className="text-xs font-tech font-bold uppercase text-zinc-300 border-b border-[#232530] pb-1.5 flex justify-between items-center">
                <span>DOGECOIN CORE OPTIONS (DAEMON SETTINGS)</span>
                <span className="text-[10px] font-mono text-zinc-500">DAEMON PORT: {formData.port} · RPC: {formData.rpcport}</span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs font-mono">
                <div>
                  <label className="text-zinc-400 block mb-1">rpcuser</label>
                  <input
                    type="text"
                    value={formData.rpcuser}
                    onChange={(e) => setFormData({ ...formData, rpcuser: e.target.value })}
                    className="w-full bg-[#121319] border border-[#3b3e4e] px-2.5 py-1.5 text-zinc-200 outline-none"
                  />
                </div>

                <div>
                  <label className="text-zinc-400 block mb-1">rpcpassword</label>
                  <input
                    type="password"
                    value={formData.rpcpassword}
                    onChange={(e) => setFormData({ ...formData, rpcpassword: e.target.value })}
                    className="w-full bg-[#121319] border border-[#3b3e4e] px-2.5 py-1.5 text-zinc-200 outline-none"
                  />
                </div>

                <div>
                  <label className="text-zinc-400 block mb-1">rpcport</label>
                  <input
                    type="number"
                    value={formData.rpcport}
                    onChange={(e) => setFormData({ ...formData, rpcport: Number(e.target.value) })}
                    className="w-full bg-[#121319] border border-[#3b3e4e] px-2.5 py-1.5 text-zinc-200 outline-none"
                  />
                </div>

                <div>
                  <label className="text-zinc-400 block mb-1">port (P2P)</label>
                  <input
                    type="number"
                    value={formData.port}
                    onChange={(e) => setFormData({ ...formData, port: Number(e.target.value) })}
                    className="w-full bg-[#121319] border border-[#3b3e4e] px-2.5 py-1.5 text-zinc-200 outline-none"
                  />
                </div>

                <div>
                  <label className="text-zinc-400 block mb-1">rpchost / bind</label>
                  <input
                    type="text"
                    value={formData.rpchost}
                    onChange={(e) => setFormData({ ...formData, rpchost: e.target.value })}
                    className="w-full bg-[#121319] border border-[#3b3e4e] px-2.5 py-1.5 text-zinc-200 outline-none"
                  />
                </div>

                <div>
                  <label className="text-zinc-400 block mb-1">rpcallowip</label>
                  <input
                    type="text"
                    value={formData.rpcallowip}
                    onChange={(e) => setFormData({ ...formData, rpcallowip: e.target.value })}
                    className="w-full bg-[#121319] border border-[#3b3e4e] px-2.5 py-1.5 text-zinc-200 outline-none"
                  />
                </div>

                <div>
                  <label className="text-zinc-400 block mb-1">txindex</label>
                  <select
                    value={formData.txindex}
                    onChange={(e) => setFormData({ ...formData, txindex: e.target.value })}
                    className="w-full bg-[#121319] border border-[#3b3e4e] px-2.5 py-1.5 text-zinc-200 outline-none"
                  >
                    <option value="1">1 (Enabled - full transaction index)</option>
                    <option value="0">0 (Disabled)</option>
                  </select>
                </div>

                <div>
                  <label className="text-zinc-400 block mb-1">server</label>
                  <select
                    value={formData.server}
                    onChange={(e) => setFormData({ ...formData, server: e.target.value })}
                    className="w-full bg-[#121319] border border-[#3b3e4e] px-2.5 py-1.5 text-zinc-200 outline-none"
                  >
                    <option value="1">1 (Accept JSON-RPC commands)</option>
                    <option value="0">0</option>
                  </select>
                </div>

                <div>
                  <label className="text-zinc-400 block mb-1">payoutInterval (seconds)</label>
                  <input
                    type="number"
                    value={formData.payoutInterval}
                    onChange={(e) => setFormData({ ...formData, payoutInterval: Number(e.target.value) })}
                    className="w-full bg-[#121319] border border-[#3b3e4e] px-2.5 py-1.5 text-zinc-200 outline-none"
                  />
                </div>

                <div>
                  <label className="text-zinc-400 block mb-1">House Cut Percentage</label>
                  <div className="bg-[#1a1b24] border border-[#3b3e4e] px-2.5 py-1.5 text-amber-400 font-bold">
                    25.00% (Strictly Enforced)
                  </div>
                </div>
              </div>
            </div>

            {/* Test RPC Ping Bar */}
            <div className="bg-[#101217] border border-[#2b2d38] p-3 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div>
                <div className="text-xs font-tech font-bold text-zinc-300">
                  DOGECOIN CORE RPC LIVE DIAGNOSTICS
                </div>
                <div className="text-[11px] font-mono text-zinc-500">
                  Status: {nodeStatus === 'connected' ? 'LIVE DAEMON ACTIVE' : 'EMULATED FALLBACK (READY FOR DAEMON)'}
                </div>
              </div>

              <button
                type="button"
                disabled={testingRpc}
                onClick={handleRunRpcTest}
                className="px-3 py-1.5 bg-[#1b2218] hover:bg-[#253320] disabled:opacity-50 text-emerald-300 border border-emerald-600 text-xs font-tech font-bold"
              >
                {testingRpc ? 'PINGING...' : 'TEST RPC CONNECTION'}
              </button>
            </div>

            {testResult && (
              <div
                className={`p-2.5 text-xs font-mono border ${
                  testResult.connected
                    ? 'bg-emerald-950/40 border-emerald-600 text-emerald-300'
                    : 'bg-amber-950/40 border-amber-600 text-amber-300'
                }`}
              >
                <div>
                  {testResult.connected
                    ? `SUCCESS: Dogecoind responded in ${testResult.latencyMs}ms!`
                    : `Daemon Offline: ${testResult.error || 'Connection refused on port ' + formData.rpcport}`}
                </div>
                {!testResult.connected && (
                  <div className="text-[11px] text-zinc-400 mt-1">
                    When you run <code className="text-amber-400">dogecoind</code> with your configuration on port {formData.rpcport}, the app automatically bridges live. The built-in cashier emulation ensures seamless local gaming in the meantime.
                  </div>
                )}
              </div>
            )}

            {saveMessage && (
              <div className="p-2.5 bg-[#291e07] border border-[#f59e0b] text-[#fbbf24] text-xs font-mono text-center">
                {saveMessage}
              </div>
            )}

            {/* Save Buttons */}
            <div className="flex justify-end gap-2 pt-2 border-t border-[#2b2d38]">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 bg-[#121318] hover:bg-[#1c1d24] border border-[#3b3e4e] text-zinc-300 text-xs font-tech"
              >
                CANCEL
              </button>
              <button
                type="submit"
                disabled={saving}
                className="px-5 py-2 bg-gradient-to-r from-[#78350f] to-[#b45309] hover:from-[#92400e] hover:to-[#d97706] text-amber-100 font-tech font-bold text-xs border border-[#fbbf24] shadow-md"
              >
                {saving ? 'SAVING...' : 'SAVE & APPLY CONFIG'}
              </button>
            </div>
          </form>
        )}

        {/* TAB 2: CLI Console */}
        {activeTab === 'cli' && (
          <div className="space-y-3">
            <div className="text-xs font-mono text-zinc-400">
              Direct JSON-RPC command line interface to Dogecoin Core.
            </div>

            <div className="flex gap-2">
              <input
                type="text"
                value={cliCommand}
                onChange={(e) => setCliCommand(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleRunCli()}
                placeholder="e.g. getbalance, getmininginfo, getnetworkhashps"
                className="flex-1 bg-[#0a0b0e] border border-[#3b3e4e] px-3 py-1.5 text-xs font-mono text-amber-300 outline-none focus:border-amber-500"
              />
              <button
                disabled={executingCli}
                onClick={handleRunCli}
                className="px-4 py-1.5 bg-[#291e07] hover:bg-[#3d2c0b] border border-[#f59e0b] text-[#fbbf24] font-tech text-xs font-bold"
              >
                {executingCli ? 'RUNNING...' : 'EXECUTE RPC'}
              </button>
            </div>

            {/* Quick RPC buttons */}
            <div className="flex flex-wrap gap-1.5 text-[11px] font-mono">
              {['getbalance', 'getmininginfo', 'getnetworkhashps', 'getblockchaininfo', 'getnewaddress', 'listtransactions'].map((cmd) => (
                <button
                  key={cmd}
                  onClick={() => {
                    setCliCommand(cmd);
                    sounds.playRelayClick();
                  }}
                  className="px-2 py-0.5 bg-[#14151c] hover:bg-[#1f212c] border border-[#2b2d38] text-zinc-400 hover:text-zinc-200"
                >
                  {cmd}
                </button>
              ))}
            </div>

            {/* Output terminal */}
            <pre className="h-64 bg-[#08090c] border border-[#2a2c38] p-3 text-xs font-mono text-zinc-300 overflow-y-auto whitespace-pre-wrap">
              {cliOutput}
            </pre>
          </div>
        )}

        {/* TAB 3: Export dogecoin.conf */}
        {activeTab === 'export' && (
          <div className="space-y-3">
            <div className="text-xs font-mono text-zinc-400">
              Save this exact file to your Dogecoin data directory (<code className="text-amber-400">~/.dogecoin/dogecoin.conf</code> on Linux/Mac or <code className="text-amber-400">%APPDATA%\Dogecoin\dogecoin.conf</code> on Windows).
            </div>

            <pre className="p-3 bg-[#08090c] border border-[#2a2c38] text-xs font-mono text-amber-300 overflow-x-auto select-all">
              {dogecoinConfRaw}
            </pre>

            <div className="flex justify-end gap-2">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(dogecoinConfRaw);
                  sounds.playCoinClink();
                  alert('dogecoin.conf copied to clipboard!');
                }}
                className="px-4 py-2 bg-[#291e07] hover:bg-[#3d2c0b] border border-[#f59e0b] text-[#fbbf24] font-tech text-xs font-bold"
              >
                COPY DOGECOIN.CONF
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
